name: Publish a release

on:
  release:
    types:
      - published


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Maven
        run: ./gradlew publishMavenPublicationToOffsetMods538Repository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/libs/*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
